name: Build and Deploy

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Use Node.js 13.13.x
      uses: actions/setup-node@v1
      with:
        node-version: 13.13.x

    - name: Build
      run: |
        npm install
        npm run build
    
    - name: deploy
      uses: JamesIves/github-pages-deploy-action@3.4.8
      with:
        ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        BRANCH: gh-pages # The branch the action should deploy to.
        FOLDER: dist

    
